config/routes.rb
LearnR::Application.routes.draw do

  post '/code_lessons/:id/update-win' => 'code_lessons#update_win'
  post '/music_lessons/:id/update-win' => 'music_lessons#update_win'
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, only: [:index, :show]
  resources :music_lessons
  resources :code_lessons

  root to: "welcome#index"
end

app/models/music_lesson.rb
class MusicLesson < ActiveRecord::Base

  has_and_belongs_to_many :users

  validates_presence_of(:points)
  validates_presence_of(:level)
  validates_presence_of(:global_level)
  validates_presence_of(:img)
  validates_presence_of(:lesson_text)
  validates_presence_of(:question_text)
  validates_presence_of(:solution_key_pattern)
  validates_presence_of(:category)
  validates_presence_of(:title)



end

app/controllers/music_lessons_controller.rb
class MusicLessonsController < ApplicationController

  before_action :require_admin_authentication, only: [:index, :new, :create, :edit, :update, :destroy]

  def index
    @music_lessons = MusicLesson.all
  end

  def show
    @lesson = MusicLesson.find(params[:id])
    if user_signed_in?
      # check to make sure user is up to this level
      user_max_music_lesson_global_level = current_user.music_lessons.pluck(:global_level).max || 0
      if @lesson.global_level > user_max_music_lesson_global_level + 1
        redirect_to root_path unless current_user.admin
      end
    else
      # To allow non-logged in users to play 1 level before signing up
      if @lesson.global_level > 1
        flash[:quick_start] = 'Please sign up to continue playing'
        redirect_to root_path
      end
    end
    respond_to do |format|
        format.html { }
        format.js   { }
        format.json { render json: @lesson.to_json }
      end
  end

  def new
    @music_lesson = MusicLesson.new
  end


  def create
    @music_lesson = MusicLesson.create(music_lesson_params)
    redirect_to @music_lesson
  end

  def edit
    @music_lesson = MusicLesson.find(params[:id])
  end

  def update
    @music_lesson = MusicLesson.find(params[:id])
    @music_lesson.update(music_lesson_params)
    redirect_to @music_lesson
  end

  def destroy
    @music_lesson = MusicLesson.find(params[:id])
    @music_lesson.destroy
    redirect_to root_path
  end

  def update_win
    lesson = MusicLesson.find(params[:id])
    if user_signed_in?
      unless current_user.music_lessons.include?(lesson)
        current_user.music_lessons << lesson
        current_user.score += lesson.points
        current_user.save
      end
      @redirect_page = 'false'
    else
      flash[:quick_start] = 'Nice Job! Please sign up to continue playing'
      @redirect_page = 'true'
    end
    next_lesson = MusicLesson.find_by(global_level: lesson.global_level + 1)
    @next_lesson_id = next_lesson.nil? ? -1 : next_lesson.id
  end

  private

    def music_lesson_params
      params.require(:music_lesson).permit(:points, :level, :img, :lesson_text,
                                           :question_text, :solution_key_pattern,
                                           :category, :title, :global_level)
    end

end

app/views/music_lessons/_form.html.erb
<%= form_for @music_lesson do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
  <%= f.label :category %>
  <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :img %>
    <%= f.text_field :img %>
  </div>
  <div class="field">
    <%= f.label :level %>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :global_level %>
    <%= f.number_field :global_level %>
  </div>
  <div class="field">
    <%= f.label :points %>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :lesson_text %>
    <%= f.text_area :lesson_text %>
  </div>
  <div class="field">
    <%= f.label :question_text %>
    <%= f.text_area :question_text %>
  </div>
  <div class="field">
    <%= f.label :solution_key_pattern %>
    <%= f.text_field :solution_key_pattern %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

app/views/music_lessons/_index.html.erb
<% music_lessons.each do |cat, lessons| %>
<h3> <%= cat %> </h3>
<ul class="one-edge-shadow">
  <% lessons.each do |lesson| %>
   <% if lesson == next_music_lesson %>
    <li><%= link_to "Lesson #{lesson.level}: #{lesson.title}", next_music_lesson %></li>
  <% else %>
   <% if completed_music_lessons.include?(lesson) %>
   <li class="completed"> <%= link_to "Lesson #{lesson.level} : #{lesson.title}", lesson %> <span id="checkmark">&#x2713</span></li>
  <% else %>
   <li class="incomplete">Lesson <%= lesson.level %>: <%= lesson.title %></li>
 <% end %>
 <% end %>
<% end %>
</ul>
<br>
<% end %>

app/views/music_lessons/_keyboard.html.erb
<div class="container" id="html-keypad">

    <div class="keyboard oct1">
      <div class="key white-key" id="c2"><div class="label">C</div></div>
      <div class="key black-key" id="c-2"> <div class="label">C#</div></div>
      <div class="key white-key" id="d2"> <div class="label">D</div></div>
      <div class="key black-key" id="d-2"> <div class="label">D#</div></div>
      <div class="key white-key" id="e2"> <div class="label">E</div></div>
      <div class="key white-key" id="f2"><div class="label">F</div></div>
      <div class="key black-key" id="f-2"> <div class="label">F#</div></div>
      <div class="key white-key" id="g2"> <div class="label">G</div></div>
      <div class="key black-key" id="g-2"> <div class="label">G#</div></div>
      <div class="key white-key" id="a3"> <div class="label">A</div></div>
      <div class="key black-key" id="a-3"> <div class="label">A#</div></div>
      <div class="key white-key" id="b3"> <div class="label">B</div></div>
    </div>
    <div class="keyboard oct2">
      <div class="key white-key" id="c3"><div class="label">C</div></div>
      <div class="key black-key" id="c-3"> <div class="label">C#</div></div>
      <div class="key white-key" id="d3"> <div class="label">D</div></div>
      <div class="key black-key" id="d-3"> <div class="label">D#</div></div>
      <div class="key white-key" id="e3"> <div class="label">E</div></div>
      <div class="key white-key" id="f3"><div class="label">F</div></div>
      <div class="key black-key" id="f-3"> <div class="label">F#</div></div>
      <div class="key white-key" id="g3"> <div class="label">G</div></div>
      <div class="key black-key" id="g-3"> <div class="label">G#</div></div>
      <div class="key white-key" id="a4"> <div class="label">A</div></div>
      <div class="key black-key" id="a-4"> <div class="label">A#</div></div>
      <div class="key white-key" id="b4"> <div class="label">B</div></div>
      <div class="key white-key" id="c5"> <div class="label">C</div></div>
    </div>
</div>


<div id="keyboard-legend">
    <img height=150px src= <%= asset_path 'music-keyboard.png' %>>
</div>

<p class="keyboard-description">Use the keys on your keyboard to play the notes according to this image chart.
<br> Press P Key to toggle SUSTAIN PEDAL!!
</p>

<!-- Below here is the javascript handling -->
<div class="player"></div>
<div>
  <select id="sound-selector">
  <option id="piano" value="piano">Piano</option>
  <option id="guitar" value="guitar">Guitar</option>
</select>
</div>

<div class="musiclesson">
<br>
  <button class="start-music-button" id="lesson">Start Lesson</button>
  <div class="lesson-player"></div>
</div>

app/views/music_lessons/_oldkeyboard.html.erb
<div class="container" id="html-keypad">

    <div class="keyboard oct1">
      <div class="key white-key" id="c2"><div class="label">C</div></div>
      <div class="key black-key" id="c-2"> <div class="label">C#</div></div>
      <div class="key white-key" id="d2"> <div class="label">D</div></div>
      <div class="key black-key" id="d-2"> <div class="label">D#</div></div>
      <div class="key white-key" id="e2"> <div class="label">E</div></div>
      <div class="key white-key" id="f2"><div class="label">F</div></div>
      <div class="key black-key" id="f-2"> <div class="label">F#</div></div>
      <div class="key white-key" id="g2"> <div class="label">G</div></div>
      <div class="key black-key" id="g-2"> <div class="label">G#</div></div>
      <div class="key white-key" id="a3"> <div class="label">A</div></div>
      <div class="key black-key" id="a-3"> <div class="label">A#</div></div>
      <div class="key white-key" id="b3"> <div class="label">B</div></div>
    </div>
    <div class="keyboard oct2">
      <div class="key white-key" id="c3"><div class="label">C</div></div>
      <div class="key black-key" id="c-3"> <div class="label">C#</div></div>
      <div class="key white-key" id="d3"> <div class="label">D</div></div>
      <div class="key black-key" id="d-3"> <div class="label">D#</div></div>
      <div class="key white-key" id="e3"> <div class="label">E</div></div>
      <div class="key white-key" id="f3"><div class="label">F</div></div>
      <div class="key black-key" id="f-3"> <div class="label">F#</div></div>
      <div class="key white-key" id="g3"> <div class="label">G</div></div>
      <div class="key black-key" id="g-3"> <div class="label">G#</div></div>
      <div class="key white-key" id="a4"> <div class="label">A</div></div>
      <div class="key black-key" id="a-4"> <div class="label">A#</div></div>
      <div class="key white-key" id="b4"> <div class="label">B</div></div>
      <div class="key white-key" id="c5"> <div class="label">C</div></div>
    </div>
</div>


<div id="keyboard-legend">
    <img height=150px src= <%= asset_path 'music-keyboard.png' %>>
</div>

<p class="keyboard-description">Use the keys on your keyboard to play the notes according to this image chart.
<br> Press P Key to toggle SUSTAIN PEDAL!!
</p>

<!-- Below here is the javascript handling -->
<div class="player"></div>
<div>
  <select id="sound-selector">
  <option id="piano" value="piano">Piano</option>
  <option id="guitar" value="guitar">Guitar</option>
</select>
</div>

<div class="musiclesson">
<br>
  <button class="start-music-button" id="lesson">Start Lesson</button>
  <div class="lesson-player"></div>
</div>

app/views/music_lessons/edit.html.erb
<h1>Edit Music Lesson</h1>
<%= render "form" %>

app/views/music_lessons/index.html.erb
<% @music_lessons.each do |music_lesson| %>
  <p><%= music_lesson.title %>
  <%= music_lesson.category %>
  <%= music_lesson.global_level %>
  <%= link_to music_lesson.title, music_lesson%>
  <%= link_to "Edit this lesson", edit_music_lesson_path(music_lesson) %>
  <%= link_to "Delete this lesson", music_lesson, method: :delete, data: { confirm: "Are you sure?" } %>
</p>
<% end %>

app/views/music_lessons/new.html.erb
<h1>New Music Lesson</h1>
<%= render "form" %>

app/views/music_lessons/show.html.erb
<div id="music-lesson-text">
  <% if user_signed_in? %>
   <p><strong>Progress:</strong> <span id='total-progress'><%= current_user.progress %></span>%</p>
   <br>
  <% end %>
  <h1><%= @lesson.title %></h1><br>
  <p>Lesson Topics: <%= @lesson.lesson_text %></p><br>
  <p class="points">Available Points: <%= @lesson.points %></p><br>
  <p>Instructions: <%= @lesson.question_text %></p>
</div>

<div class="container" id="keyboard-container">

      <div class="canvas"  id="keyboard-partial">
        <%= render 'keyboard' %>
      </div>

  <div id="music-lessons-page"></div>

    <%= content_tag(:div, class: "music-lesson-id", 'data-id' => @lesson.id) do %>
    <% end %>

</div>

app/views/music_lessons/update_win.js.erb
if ("<%= @redirect_page %>" === "true") {
  window.location.replace('/');
} else {

  if ($('.win-message').length < 1) {
    $("<div class='win-message one-edge-shadow'><p>Way to go!</p></div>").hide().prependTo($('#keyboard-container')).fadeIn();

    if (<%= @next_lesson_id %> !== -1) {
      $('.win-message').append("<a href='/music_lessons/<%= @next_lesson_id %>'>Next Lesson</a>");
    } else {
      $('.win-message').append("<p>You've completed all lessons! Check back for more in the future!</p>");
    }
  }

  $('#total-score').fadeOut(function(){
    $(this).text(<%= current_user.score if current_user %>).fadeIn();
  });

  $('#total-progress').fadeOut(function(){
    $(this).text(<%= current_user.progress if current_user %>).fadeIn();
  });
}