config/routes.rb
LearnR::Application.routes.draw do

  post '/code_lessons/:id/update-win' => 'code_lessons#update_win'
  post '/music_lessons/:id/update-win' => 'music_lessons#update_win'
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, only: [:index, :show]
  resources :music_lessons
  resources :code_lessons

  root to: "welcome#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # attr_accessible :username, :name, :email, :password, :password_confirmation, :remember_me

  # Custom Validations
  validates(:name, :username, presence: true)
  validates(:username, uniqueness: true)
  validates(:avatar, presence: true)

  has_and_belongs_to_many :code_lessons
  has_and_belongs_to_many :music_lessons

  before_create :initialize_score

  def progress
    result = 0
    total_course_lessons = MusicLesson.all.size + CodeLesson.all.size
    total_completed_lessons = self.music_lessons.size + self.code_lessons.size
    begin
      result = (total_completed_lessons / total_course_lessons.to_f * 100).to_i
    rescue
    end
    result
  end

  private

    def initialize_score
      self.score = 0
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def index
    @users = User.all
    @sorted_users = User.order(score: :desc)
   end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html {}
      format.json { render json: @user.to_json }
    end

    @code_lessons = CodeLesson.all.group_by(&:category)
    @completed_code_lessons = @user.code_lessons
    if @user.code_lessons.empty?
      @next_code_lesson = CodeLesson.find_by(global_level: 1)
    else
      @next_code_lesson = CodeLesson.find_by(global_level: @completed_code_lessons.pluck(:global_level).max + 1)
    end

    @music_lessons = MusicLesson.all.group_by(&:category)
    @completed_music_lessons = @user.music_lessons
    if @user.music_lessons.empty?
      @next_music_lesson = MusicLesson.find_by(global_level: 1)
    else
      @next_music_lesson = MusicLesson.find_by(global_level: @completed_music_lessons.pluck(:global_level).max + 1)
    end
  end


end

app/views/users/index.html.erb
<div id="leaderboard">
<div><h2>Leaderboard</h2><div>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>High Score</th>
    </tr>
  </thead>
  <tbody>
<% @sorted_users.each do |user| %>
  <tr>
    <td><strong><%= user.username %></strong></td>
    <td><strong><%= user.score %></strong></td>
  </tr>
<% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<div id="user-sidebar" class="one-edge-shadow">
  <h1><%= @user.username %></h1>
  <%= link_to 'Edit Info', edit_user_registration_path %>
  <%= link_to 'Leaderboard', users_path %>
</div>

<div id="show-container">
  <div id="lesson-box">
    <div id="code-show-section" class="one-edge-shadow">
      <h2>Code Lessons</h2>
      <%= render partial: 'code_lessons/index', locals: {code_lessons: @code_lessons, completed_code_lessons: @completed_code_lessons, next_code_lesson: @next_code_lesson} %>
    </div>
    <div id="music-show-section" class="one-edge-shadow">
      <h2>Music Lessons</h2>
      <%= render partial: 'music_lessons/index', locals: { music_lessons: @music_lessons, completed_music_lessons: @completed_music_lessons, next_music_lesson: @next_music_lesson} %>
    </div>

     <%= content_tag(:div, class: "user-id", 'data-id' => @user.id) do %>
      <% end %>
  </div>
</div>

  <% if current_user.try(:admin?) %>
  <div id="admin-panel">
    <%= link_to "All Music Lessons", music_lessons_path %><br>
    <%= link_to "Create a new Music Lesson", new_music_lesson_path %><br>
    <%= link_to "All Code Lessons", code_lessons_path %><br>
    <%= link_to "Create a new Code Lesson", new_code_lesson_path %>
    <div>
  <% end %>