config/routes.rb
LearnR::Application.routes.draw do

  post '/code_lessons/:id/update-win' => 'code_lessons#update_win'
  post '/music_lessons/:id/update-win' => 'music_lessons#update_win'
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, only: [:index, :show]
  resources :music_lessons
  resources :code_lessons

  root to: "welcome#index"
end

app/models/code_lesson.rb
class CodeLesson < ActiveRecord::Base

    has_and_belongs_to_many :users

    validates_presence_of(:lesson_text)
    validates_presence_of(:question_text)
    validates_presence_of(:img)
    validates_presence_of(:level)
    validates_presence_of(:global_level)
    validates_presence_of(:points)
    validates_presence_of(:start_row)
    validates_presence_of(:start_col)
    validates_presence_of(:solution_row)
    validates_presence_of(:solution_col)
    validates_presence_of(:title)
    validates_presence_of(:category)

end

app/controllers/code_lessons_controller.rb
class CodeLessonsController < ApplicationController

  before_action :require_admin_authentication, only: [:index, :new, :create, :edit, :update, :destroy]

  def index
    @code_lessons = CodeLesson.all
  end

  def show
    @lesson = CodeLesson.find(params[:id])
    if user_signed_in?
      # check to make sure user is up to this level
      user_max_code_lesson_global_level = current_user.code_lessons.pluck(:global_level).max || 0
      if @lesson.global_level > (user_max_code_lesson_global_level + 1)
        redirect_to root_path unless current_user.admin
      end
    else
      # To allow non-logged in users to play 1 level before signing up
      if @lesson.global_level > 1
        flash[:quick_start] = 'Please sign up to continue playing'
        redirect_to root_path
      end
    end
    respond_to do |format|
      format.html { }
      format.js   { }
      format.json { render json: @lesson.to_json }
    end
  end

  def new
    @code_lesson = CodeLesson.new
  end

  def create
    @code_lesson = CodeLesson.create(code_lesson_params)
    redirect_to @code_lesson
  end

  def edit
    @code_lesson = CodeLesson.find(params[:id])
  end

  def update
    @code_lesson = CodeLesson.find(params[:id])
    @code_lesson.update(code_lesson_params)
    redirect_to @code_lesson
  end

  def destroy
    @code_lesson = CodeLesson.find(params[:id])
    @code_lesson.destroy
    redirect_to root_path
  end

  def update_win
    lesson = CodeLesson.find(params[:id])
    if user_signed_in?
      unless current_user.code_lessons.include?(lesson)
        current_user.code_lessons << lesson
        current_user.score += lesson.points
        current_user.save
      end
      @redirect_page = 'false'
    else
      flash[:quick_start] = 'Nice Job! Please sign up to continue playing'
      @redirect_page = 'true'
    end
    next_lesson = CodeLesson.find_by(global_level: lesson.global_level + 1)
    @next_lesson_id = next_lesson.nil? ? -1 : next_lesson.id
  end

  private

  def code_lesson_params
    params.require(:code_lesson).permit(:points, :level, :img, :map_code,
                                        :lesson_text, :question_text, :start_row,
                                        :start_col, :solution_row, :solution_col,
                                        :category, :title, :global_level)
  end

end

app/views/code_lessons/_form.html.erb
<%= form_for @code_lesson do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
  <%= f.label :category %>
  <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :img %>
    <%= f.text_field :img %>
  </div>
  <div class="field">
    <%= f.label :map_code %>
    <%= f.text_field :map_code %>
  </div>
  <div class="field">
    <%= f.label :level %>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :global_level %>
    <%= f.number_field :global_level %>
  </div>
  <div class="field">
    <%= f.label :points %>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :lesson_text %>
    <%= f.text_area :lesson_text %>
  </div>
  <div class="field">
    <%= f.label :question_text %>
    <%= f.text_area :question_text %>
  </div>
  <div class="field">
    <%= f.label :start_row %>
    <%= f.text_field :start_row %>
  </div>
  <div class="field">
    <%= f.label :start_col %>
    <%= f.text_field :start_col %>
  </div>
  <div class="field">
    <%= f.label :solution_row %>
    <%= f.text_field :solution_row %>
  </div>
  <div class="field">
    <%= f.label :solution_col %>
    <%= f.text_field :solution_col %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

app/views/code_lessons/_index.html.erb
<% code_lessons.each do |cat, lessons| %>
  <h3><%= cat %></h3>
  <ul>
  <% lessons.each do |lesson| %>
  <% if lesson == next_code_lesson %>
    <li class="one-edge-shadow"><%= link_to "Lesson #{lesson.level}: #{lesson.title}", next_code_lesson %></li>
  <% else %>
    <% if completed_code_lessons.include?(lesson) %>
      <li class="completed one-edge-shadow"> <%= link_to "Lesson #{lesson.level}: #{lesson.title}", lesson %><span id="checkmark"></%> &#x2713</span></li>
    <% else %>
      <li class="incomplete one-edge-shadow">Lesson <%= lesson.level %>: <%= lesson.title %></li>
    <% end %>
    <% end %>
  <% end %>
  </ul>
  <br>
<% end %>

app/views/code_lessons/edit.html.erb
<h1>Edit Code Lesson</h1>
<%= render "form" %>

app/views/code_lessons/index.html.erb
<% @code_lessons.each do |code_lesson| %>
  <p><%= code_lesson.title %>
  <%= code_lesson.category %>
  <%= code_lesson.global_level %>
  <%= link_to code_lesson.title, code_lesson%>
  <%= link_to "Edit this lesson", edit_code_lesson_path(code_lesson) %>
  <%= link_to "Delete this lesson", code_lesson, method: :delete, data: { confirm: "Are you sure?" } %>
</p>
<% end %>

app/views/code_lessons/new.html.erb
<h1>New Code Lesson</h1>
<%= render "form" %>

app/views/code_lessons/show.html.erb
<div class="container">
    <div class="canvas">
      <canvas id="lessoncanvas" height="600" width="600"></canvas>
      <br><br>
      <p>(Don't see the robot? Try refreshing)</p>
    </div>
    <div id="code-lesson-text">
      <% if user_signed_in? %>
        <p><strong>Progress:</strong> <span id='total-progress'><%= current_user.progress %></span>%</p>
        <br>
      <% end %>
      <h1><%= @lesson.title %></h1>

      <p><strong>Lesson Topic</strong>: <%= @lesson.lesson_text %></p>
      <br>
      <p class="points"><strong>Available Points:</strong> <%= @lesson.points %></p>
      <br>
      <p><strong>Instructions:</strong> <%= @lesson.question_text %></p>
      <%= content_tag(:div, class: "lesson-id", 'data-id' => @lesson.id) do %>
      <% end %>
      <br>
      <div class="errors"></div>
      <%= form_tag( @lesson, method: :get, remote: true) do |f| %>

      <%= label_tag(:answer, "Enter your answer") %>
      <%= text_area_tag :answer, nil, size: "50x10", id: 'code-area' %>
      <br>
      <%= submit_tag( "Submit Answer") %>

      <% end %>
      <%= link_to "Reset", code_lesson_path %>
  </div>

    <div id="code-lessons-page"></div>
</div>

app/views/code_lessons/show.js.erb
//Logic for moving the player

var orientationChanger = {east:  'north',
                          north: 'west',
                          west:  'south',
                          south: 'east'};

var directionPicker = {east:  moveImageOneUnitEast,
                       west:  moveImageOneUnitWest,
                       north: moveImageOneUnitNorth,
                       south: moveImageOneUnitSouth};

var commandConverter = {'turnLeft': turnLeft,
                        'moveForward': moveForward};

function throwError() {
  $('.errors').empty();
  $('.errors').append('<p class="code-error">Something went wrong<br>Check your spelling and punctuation!</p>');
}

function runCommands(commands) {
  var counter = 0;
  var i = setInterval(function(){
    if (counter >= 0) {
      if (commandConverter[commands[counter]]) {
        commandConverter[commands[counter]](robot);
        stage.update();
      } else {
        throwError();
        clearInterval(i);
      }
    }
    counter ++;

    if (counter >= commands.length) {
      clearInterval(i);
      checkWin();
    }
  }, 500);
}

function turnLeft(image) {
  orientation = orientationChanger[orientation];
  image.rotation = image.rotation - 90;
  stage.update();
}

function moveForward(image) {
  directionPicker[orientation](image);
}

function moveImageOneUnitEast(image) {
  if (image.x + XGRIDUNIT < stage.canvas.width) {
    if (map[gridRow][gridCol + 1] !== 1) {
      image.x += XGRIDUNIT;
      gridCol += 1;
    }
  }
}

function moveImageOneUnitWest(image) {
  if (image.x - XGRIDUNIT > 0) {
    if (map[gridRow][gridCol - 1] !== 1) {
      image.x -= XGRIDUNIT;
      gridCol -= 1;
    }
  }
}

function moveImageOneUnitSouth(image) {
  if (image.y + YGRIDUNIT < stage.canvas.height) {
    if (map[gridRow + 1][gridCol] !== 1) {
      image.y += YGRIDUNIT;
      gridRow += 1;
    }
  }
}

function moveImageOneUnitNorth(image) {
  if (image.y - YGRIDUNIT > 0) {
    if (map[gridRow - 1][gridCol] !== 1) {
      image.y -= YGRIDUNIT;
      gridRow -= 1;
    }
  }
}

function checkWin() {
  if (gridRow === solutionRow && gridCol === solutionCol) {
    $.ajax({
      url: ('/code_lessons/' + lessonID + '/update-win'),
      method: 'post'
    });
  }
}

function parseCommands(text) {
  var lines = text.split(";");
  var masterCommandList = [];
  for (var i = 0; i < lines.length - 1; i++) {
    var command = lines[i].trim();
    if (command.indexOf("(") === -1) {
      throwError();
      break;
    } else if (command.indexOf(")") === -1) {
      throwError();
      break;
    } else {
      var commandString = command.split("(")[0];
      var argString = command.split("(")[1].split(")")[0];
      argString = argString === "" ? 1 : argString;
      for (var j = 0; j < Number(argString); j++) {
        masterCommandList.push(commandString);
      }
    }
  }
  runCommands(masterCommandList);
}

$('.errors').empty();
parseCommands($('textarea').val());

app/views/code_lessons/update_win.js.erb
if ("<%= @redirect_page %>" === "true") {
  window.location.replace('/');
} else {
  if ($('.win-message').length < 1) {
    $("<div class='win-message one-edge-shadow'><p>Way to go!</p></div>").hide().prependTo($('.container')).fadeIn();

    if (<%= @next_lesson_id %> !== -1) {
      $('.win-message').append("<a href='/code_lessons/<%= @next_lesson_id %>'>Next Lesson</a>");
    } else {
      $('.win-message').append("<p>You've completed all lessons! Check back for more in the future!</p>");
    }
  }

  $('#total-score').fadeOut(function(){
    $(this).text(<%= current_user.score if current_user %>).fadeIn();
  });

  $('#total-progress').fadeOut(function(){
    $(this).text(<%= current_user.progress if current_user %>).fadeIn();
  });
}